# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horaris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('assignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horaris.Facultad')),
            ],
        ),
        migrations.RenameField(
            model_name='carrera',
            old_name='facu',
            new_name='facultad',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horaris.Carrera'),
        ),
    ]
