# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horaris', '0004_quatri'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='codiUPC',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
    ]
