# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horaris', '0005_auto_20170519_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='codiUPC',
            field=models.CharField(max_length=50),
        ),
    ]
