# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horaris', '0006_auto_20170519_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='cuatri',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='horaris.Quatri'),
            preserve_default=False,
        ),
    ]
