# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horaris', '0007_asignatura_cuatri'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='loaded',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
