# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horaris', '0010_auto_20170523_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='assignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horaris.Asignatura'),
        ),
    ]
