# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horaris', '0011_auto_20170523_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='carrera',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='horaris.Carrera'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='cuatri',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='horaris.Quatri'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='loaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='facultad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='horaris.Facultad'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='assignatura',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='horaris.Asignatura'),
        ),
        migrations.AlterField(
            model_name='quatri',
            name='facultad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='horaris.Facultad'),
        ),
    ]
