# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horaris', '0012_auto_20170530_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='codigo',
            field=models.CharField(max_length=32),
        ),
    ]
